hbase.zookeeper.quorum: 112.124.60.26:2181
zookeeper.znode.parent: /hbase
database.pool.size: 20
broker.pool.size: 10
broker.check.interval: 5

trader.account.id: cheetah
trader.execl.base.dir: "/home/eryk/stocks"
trader.trading.day.count: 1000

dashboard:
  - "601886"
  - "600376"
  - "600160"
  - "300217"
  - "600270"
  - "300327"
  - "600887"
  - "600030"

# cron格式
# Seconds Minutes Hours DayOfMonth Month DayOfWeek Year
#   ,-*     ,-*    ,-*    ,-*?/LW   ,-*   ,-*?/L#   ,-*
jobs:
  stockListDownload:
    classname: com.zhaijiong.stock.scheduler.StockListDownloadJob
    cron: "0 0 0 ? * 2-6 *"
  dailyDataDownload:
    classname: com.zhaijiong.stock.scheduler.DailyDataDownloadJob
    cron: "0 0/5 9-15 ? * 2-6 *"
  stock15MinuteDataDownload:
    classname: com.zhaijiong.stock.scheduler.StockMinuteDataDownloadJob
    type: "15"
    cron: "0 0/15 9-15 ? * 2-6 *"
  DailyIndicatorsCompute:
    classname: com.zhaijiong.stock.scheduler.IndicatorsComputeJob
    cron: "0 0 3 ? * 2-6 *"
  FinanceDataDownload:
    classname: com.zhaijiong.stock.scheduler.FinanceDataDownloadJob
    cron: "0 0 0 1 * ? *"
  moneyFlowDataDownload:
    classname: com.zhaijiong.stock.scheduler.MoneyFlowDataDownloadJob
    cron: "0 0/15 9-15 ? * 2-6 *"